In [1]:
import pandas as pd

In [2]:
years = [1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000]
verbs = ['get','find','show','put','carry','receive','offer']
genres = ['NF', 'FIC', 'MAG']

In [3]:
for v in verbs:
    for y in years:
        for g in genres:
            print(v + ' '+ str(y) + "algo"+ ' '+ g)

get 1820algo NF
get 1820algo FIC
get 1820algo MAG
get 1830algo NF
get 1830algo FIC
get 1830algo MAG
get 1840algo NF
get 1840algo FIC
get 1840algo MAG
get 1850algo NF
get 1850algo FIC
get 1850algo MAG
get 1860algo NF
get 1860algo FIC
get 1860algo MAG
get 1870algo NF
get 1870algo FIC
get 1870algo MAG
get 1880algo NF
get 1880algo FIC
get 1880algo MAG
get 1890algo NF
get 1890algo FIC
get 1890algo MAG
get 1900algo NF
get 1900algo FIC
get 1900algo MAG
get 1910algo NF
get 1910algo FIC
get 1910algo MAG
get 1920algo NF
get 1920algo FIC
get 1920algo MAG
get 1930algo NF
get 1930algo FIC
get 1930algo MAG
get 1940algo NF
get 1940algo FIC
get 1940algo MAG
get 1950algo NF
get 1950algo FIC
get 1950algo MAG
get 1960algo NF
get 1960algo FIC
get 1960algo MAG
get 1970algo NF
get 1970algo FIC
get 1970algo MAG
get 1980algo NF
get 1980algo FIC
get 1980algo MAG
get 1990algo NF
get 1990algo FIC
get 1990algo MAG
get 2000algo NF
get 2000algo FIC
get 2000algo MAG
find 1820algo NF
find 1820algo FIC
find 1820algo MAG
find 1830algo NF
find 1830algo FIC
find 1830algo MAG
find 1840algo NF
find 1840algo FIC
find 1840algo MAG
find 1850algo NF
find 1850algo FIC
find 1850algo MAG
find 1860algo NF
find 1860algo FIC
find 1860algo MAG
find 1870algo NF
find 1870algo FIC
find 1870algo MAG
find 1880algo NF
find 1880algo FIC
find 1880algo MAG
find 1890algo NF
find 1890algo FIC
find 1890algo MAG
find 1900algo NF
find 1900algo FIC
find 1900algo MAG
find 1910algo NF
find 1910algo FIC
find 1910algo MAG
find 1920algo NF
find 1920algo FIC
find 1920algo MAG
find 1930algo NF
find 1930algo FIC
find 1930algo MAG
find 1940algo NF
find 1940algo FIC
find 1940algo MAG
find 1950algo NF
find 1950algo FIC
find 1950algo MAG
find 1960algo NF
find 1960algo FIC
find 1960algo MAG
find 1970algo NF
find 1970algo FIC
find 1970algo MAG
find 1980algo NF
find 1980algo FIC
find 1980algo MAG
find 1990algo NF
find 1990algo FIC
find 1990algo MAG
find 2000algo NF
find 2000algo FIC
find 2000algo MAG
show 1820algo NF
show 1820algo FIC
show 1820algo MAG
show 1830algo NF
show 1830algo FIC
show 1830algo MAG
show 1840algo NF
show 1840algo FIC
show 1840algo MAG
show 1850algo NF
show 1850algo FIC
show 1850algo MAG
show 1860algo NF
show 1860algo FIC
show 1860algo MAG
show 1870algo NF
show 1870algo FIC
show 1870algo MAG
show 1880algo NF
show 1880algo FIC
show 1880algo MAG
show 1890algo NF
show 1890algo FIC
show 1890algo MAG
show 1900algo NF
show 1900algo FIC
show 1900algo MAG
show 1910algo NF
show 1910algo FIC
show 1910algo MAG
show 1920algo NF
show 1920algo FIC
show 1920algo MAG
show 1930algo NF
show 1930algo FIC
show 1930algo MAG
show 1940algo NF
show 1940algo FIC
show 1940algo MAG
show 1950algo NF
show 1950algo FIC
show 1950algo MAG
show 1960algo NF
show 1960algo FIC
show 1960algo MAG
show 1970algo NF
show 1970algo FIC
show 1970algo MAG
show 1980algo NF
show 1980algo FIC
show 1980algo MAG
show 1990algo NF
show 1990algo FIC
show 1990algo MAG
show 2000algo NF
show 2000algo FIC
show 2000algo MAG
put 1820algo NF
put 1820algo FIC
put 1820algo MAG
put 1830algo NF
put 1830algo FIC
put 1830algo MAG
put 1840algo NF
put 1840algo FIC
put 1840algo MAG
put 1850algo NF
put 1850algo FIC
put 1850algo MAG
put 1860algo NF
put 1860algo FIC
put 1860algo MAG
put 1870algo NF
put 1870algo FIC
put 1870algo MAG
put 1880algo NF
put 1880algo FIC
put 1880algo MAG
put 1890algo NF
put 1890algo FIC
put 1890algo MAG
put 1900algo NF
put 1900algo FIC
put 1900algo MAG
put 1910algo NF
put 1910algo FIC
put 1910algo MAG
put 1920algo NF
put 1920algo FIC
put 1920algo MAG
put 1930algo NF
put 1930algo FIC
put 1930algo MAG
put 1940algo NF
put 1940algo FIC
put 1940algo MAG
put 1950algo NF
put 1950algo FIC
put 1950algo MAG
put 1960algo NF
put 1960algo FIC
put 1960algo MAG
put 1970algo NF
put 1970algo FIC
put 1970algo MAG
put 1980algo NF
put 1980algo FIC
put 1980algo MAG
put 1990algo NF
put 1990algo FIC
put 1990algo MAG
put 2000algo NF
put 2000algo FIC
put 2000algo MAG
carry 1820algo NF
carry 1820algo FIC
carry 1820algo MAG
carry 1830algo NF
carry 1830algo FIC
carry 1830algo MAG
carry 1840algo NF
carry 1840algo FIC
carry 1840algo MAG
carry 1850algo NF
carry 1850algo FIC
carry 1850algo MAG
carry 1860algo NF
carry 1860algo FIC
carry 1860algo MAG
carry 1870algo NF
carry 1870algo FIC
carry 1870algo MAG
carry 1880algo NF
carry 1880algo FIC
carry 1880algo MAG
carry 1890algo NF
carry 1890algo FIC
carry 1890algo MAG
carry 1900algo NF
carry 1900algo FIC
carry 1900algo MAG
carry 1910algo NF
carry 1910algo FIC
carry 1910algo MAG
carry 1920algo NF
carry 1920algo FIC
carry 1920algo MAG
carry 1930algo NF
carry 1930algo FIC
carry 1930algo MAG
carry 1940algo NF
carry 1940algo FIC
carry 1940algo MAG
carry 1950algo NF
carry 1950algo FIC
carry 1950algo MAG
carry 1960algo NF
carry 1960algo FIC
carry 1960algo MAG
carry 1970algo NF
carry 1970algo FIC
carry 1970algo MAG
carry 1980algo NF
carry 1980algo FIC
carry 1980algo MAG
carry 1990algo NF
carry 1990algo FIC
carry 1990algo MAG
carry 2000algo NF
carry 2000algo FIC
carry 2000algo MAG
receive 1820algo NF
receive 1820algo FIC
receive 1820algo MAG
receive 1830algo NF
receive 1830algo FIC
receive 1830algo MAG
receive 1840algo NF
receive 1840algo FIC
receive 1840algo MAG
receive 1850algo NF
receive 1850algo FIC
receive 1850algo MAG
receive 1860algo NF
receive 1860algo FIC
receive 1860algo MAG
receive 1870algo NF
receive 1870algo FIC
receive 1870algo MAG
receive 1880algo NF
receive 1880algo FIC
receive 1880algo MAG
receive 1890algo NF
receive 1890algo FIC
receive 1890algo MAG
receive 1900algo NF
receive 1900algo FIC
receive 1900algo MAG
receive 1910algo NF
receive 1910algo FIC
receive 1910algo MAG
receive 1920algo NF
receive 1920algo FIC
receive 1920algo MAG
receive 1930algo NF
receive 1930algo FIC
receive 1930algo MAG
receive 1940algo NF
receive 1940algo FIC
receive 1940algo MAG
receive 1950algo NF
receive 1950algo FIC
receive 1950algo MAG
receive 1960algo NF
receive 1960algo FIC
receive 1960algo MAG
receive 1970algo NF
receive 1970algo FIC
receive 1970algo MAG
receive 1980algo NF
receive 1980algo FIC
receive 1980algo MAG
receive 1990algo NF
receive 1990algo FIC
receive 1990algo MAG
receive 2000algo NF
receive 2000algo FIC
receive 2000algo MAG
offer 1820algo NF
offer 1820algo FIC
offer 1820algo MAG
offer 1830algo NF
offer 1830algo FIC
offer 1830algo MAG
offer 1840algo NF
offer 1840algo FIC
offer 1840algo MAG
offer 1850algo NF
offer 1850algo FIC
offer 1850algo MAG
offer 1860algo NF
offer 1860algo FIC
offer 1860algo MAG
offer 1870algo NF
offer 1870algo FIC
offer 1870algo MAG
offer 1880algo NF
offer 1880algo FIC
offer 1880algo MAG
offer 1890algo NF
offer 1890algo FIC
offer 1890algo MAG
offer 1900algo NF
offer 1900algo FIC
offer 1900algo MAG
offer 1910algo NF
offer 1910algo FIC
offer 1910algo MAG
offer 1920algo NF
offer 1920algo FIC
offer 1920algo MAG
offer 1930algo NF
offer 1930algo FIC
offer 1930algo MAG
offer 1940algo NF
offer 1940algo FIC
offer 1940algo MAG
offer 1950algo NF
offer 1950algo FIC
offer 1950algo MAG
offer 1960algo NF
offer 1960algo FIC
offer 1960algo MAG
offer 1970algo NF
offer 1970algo FIC
offer 1970algo MAG
offer 1980algo NF
offer 1980algo FIC
offer 1980algo MAG
offer 1990algo NF
offer 1990algo FIC
offer 1990algo MAG
offer 2000algo NF
offer 2000algo FIC
offer 2000algo MAG

In [4]:
f = open("AlgoPartitionsByGenre3.sql", "a+")
for v in verbs:
    for y in years:
        for g in genres:
#             print(v + ' '+ str(y)+'algo' + ' '+ g)
            sqlQuery = """
COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM """ + 'p' + str(y) + "algo" + """ as c, lexicon as l, sources as s
where l.lemma like '""" + v + """'
and c.w1 = l.wid and s.textid = c.source and s.genre = '""" + g + """'
UNION ALL
SELECT c.w3 FROM """ + 'p' + str(y) + "algo" + """ as c, lexicon as l, sources as s
where l.lemma like '""" + v + """'
and c.w1 = l.wid and s.textid = c.source and s.genre = '""" + g + """'
UNION ALL
SELECT c.w4 FROM """ + 'p' + str(y) + "algo" + """ as c, lexicon as l, sources as s
where l.lemma like '""" + v + """'
and c.w1 = l.wid and s.textid = c.source and s.genre = '""" + g + """'
UNION ALL
SELECT c.w5 FROM """ + 'p' + str(y) + "algo" + """ as c, lexicon as l, sources as s
where l.lemma like '""" + v + """'
and c.w1 = l.wid and s.textid = c.source and s.genre = '""" + g + """'
UNION ALL
SELECT c.w6 FROM """ + 'p' + str(y) + "algo" """ as c, lexicon as l, sources as s
where l.lemma like '""" + v + """'
and c.w1 = l.wid and s.textid = c.source and s.genre = '""" + g + """'
) a, lexicon b where 
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO """ + "\'/var/lib/postgresql/algoResult/" + v + str(y) + g +".csv\' CSV HEADER;\n"

            print(sqlQuery)
            f.write(sqlQuery)
f.close()

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w3 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w4 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w5 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w6 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1820NF.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w3 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w4 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w5 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w6 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1820FIC.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w3 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w4 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w5 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w6 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1820MAG.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w3 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w4 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w5 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w6 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1830NF.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w3 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w4 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w5 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w6 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1830FIC.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w3 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w4 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w5 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w6 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1830MAG.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w3 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w4 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w5 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w6 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1840NF.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w3 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w4 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w5 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w6 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1840FIC.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w3 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w4 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w5 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w6 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1840MAG.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w3 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w4 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w5 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w6 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1850NF.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w3 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w4 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w5 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w6 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1850FIC.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w3 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w4 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w5 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w6 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1850MAG.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w3 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w4 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w5 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w6 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1860NF.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w3 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w4 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w5 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w6 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1860FIC.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w3 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w4 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w5 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w6 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1860MAG.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w3 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w4 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w5 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w6 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1870NF.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w3 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w4 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w5 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w6 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1870FIC.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w3 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w4 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w5 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w6 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/get1870MAG.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1880algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w3 FROM p1880algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w4 FROM p1880algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w5 FROM p1880algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w6 FROM p1880algo as c, lexicon as l, sources as s
where l.lemma like 'get'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')